# netlify.toml

# 解决验证文件问题
[[redirects]]
  from = "/WW_verify_wcxe1Oew87cdo756.txt"
  to = "/WW_verify_wcxe1Oew87cdo756.txt"
  status = 200
  force = true

# 防止构建系统忽略此文件
[[headers]]
  for = "/WW_verify_wcxe1Oew87cdo756.txt"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

